### ISSUE TITLE
Hii I have Similar Specs laptop .. hp omen dc 1093tx 

### ISSUE THREAD

**Issue by ankurbaghel** [lunjielee/Opencore-HP-Omen-15-2020#12]
Hello i want to install big sur in my laptop
Specs are below 
 I7 9750H
8 gb ram
256gb ssd
Synaptics touchpad
Intel wifi bt

Can i use your efi and start fine tuning it ??

According to my laptop

Plz help me out

**Comment by ankurbaghel** [comment]
hello  i have installed mac os BIG SUR on my laptop using your EFI folder evrything works grate 
except these things ===

battery indication and after starting laptop i got error massage ''non Hp battery error 
touchpad is not working
internal speaker is not working but audio in headphone is perfect
internal 1 TB HDD is not Detected
processor fan optimization 
sleep wake hibernation Function is also not working

what works ====


wifi and bluetooth works flawlessly
audio control with shortcut
brightness Control with keys 



also i love to know how to add delay in clover bootloader menu to select another operating system for booting 
and Nvram clear icon as well 


Did you patched DSDT for working Battery Please Let me Know


Regards - Kid

**Comment by lunjielee** [comment]
Hi @ankurbaghel ,
Sorry to reply to you this late, I hope you have solved these problems, if not, here are some of my suggestions.

1. battery indication
No, I didn't patch my DSDT for the battery indicator to work. Instead, I created an SSDT hotpatch to make it possible. Here is a guide [How to patch DSDT for working battery status](https://www.tonymacx86.com/threads/guide-how-to-patch-dsdt-for-working-battery-status.116102/) from RehabMan, it's pretty outdated though.
2. touchpad
Yeah, again touchpad also requires specific patches for the specific system. Here is the [installation guide](https://voodooi2c.github.io/#Installation/Installation) for VoodooI2C
3. internal speaker
Change `layout-id` in `config.plist`, Here is [the guide](https://github.com/acidanthera/AppleALC/wiki/Installation-and-usage) from **AppleALC**

Also my file are only compatible with OpenCore, so some other problems might be caused by that.
Hope this helps.
