### ISSUE TITLE
dGPU OFF help

### ISSUE THREAD

**Issue by bouhka** [lunjielee/Opencore-HP-Omen-15-2020#14]
Hi Lunjielee.  .  I would like to know what battery life it has, as a check to turn off dDGP.  Which kext I update to turn off dGPU.  I have a legion with 10750h, I do not get more than two hours of battery. Thank you for your help.

**Comment by lunjielee** [comment]
Hi @bouhka, you can use an `aml file` to turn off your dGPU, here is my version of [SSDT-dGPU-Off.aml](https://github.com/lunjielee/Opencore-HP-Omen-15-2020/raw/master/EFI/OC/ACPI/SSDT-dGPU-Off.aml). Load and reboot then you should have your dGPU turned off.

If my version of `SSDT-dGPU-Off.aml` is not working (Usually this is because you and I have different dGPU BIOS device name). In that case, here is the guide [Disabling laptop dGPUs (SSDT-dGPU-Off/NoHybGfx)](https://dortania.github.io/Getting-Started-With-ACPI/Laptops/laptop-disable.html) for you that you could follow so that you can create your own version of SSDT-dGPU-Off.aml

Hope this helps!
