### ISSUE TITLE
Is it safe to boot Windows from OpenCore Bootloader

### ISSUE THREAD

**Issue by jogiji** [lunjielee/Opencore-HP-Omen-15-2020#17]
Hi @lunjielee .. Is it safe to boot windows directly from opencore bootloader ?

**Comment by taurzon5** [comment]
You can but you shouldn't. For me on my HP OMEN 15, it shows Macbookpro16,4 as my device name instead of 15-ek0xxx series laptop. This also shows up in HP support assistant. Windows may also see this as a configuration change will disable the license installed. 
Though Windows wil work perfectly fine.
There maybe a way to not inject properties in Windows but I haven't figured out. If you have an OMEN 15 EK laptop, open boot menu while starting up, (press F9 repeatedly before the Logo) choose windows bootloader from there.

**Comment by Warmerfare** [comment]
@jogiji @khushtaur3123 

You can actually. If you do not prefer using bootcamp and / or want windows to see your computers original serial number instead of the injected SMbios one you should make the following changes to your config.plist:

Enable Kernel > Quirks > CustomSMBIOSGuid

Change PlatformInfo > UpdateSMBIOSMode to Custom

I personaly use opencore to boot my original by hp installed windows os without SMbios injection (so the keyboard lighting and fans can be controlled correctly) and my macOS with SMbios injected. I also installed bootcamp tools on windows to allow me to switch between os x and windows trough software instead of pressing hotkeys during bootup. This gave me a seamless mac like expercience.

Note: Bootcamp installations / Installing windows trough bootcamp won't work after doing so.

**Comment by taurzon5** [comment]
@Warmerfare I actually didn't know about it. Thanks for telling.

**Comment by jogiji** [comment]
Closing this issue.
